name: DeployAPINUR

on:
  push:
    branches: [ "main" ] # Rama principal si es diferente

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Ejecutamos comandos via SSH
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} << 'EOF'
        # Cambiar al directorio del proyecto
        cd /home/Proyectos/Mod3Nutricenter || exit
        
        # Detener y eliminar el contenedor si existe
        if [ "$(docker ps -aq -f name=nutricenter-container)" ]; then
            docker stop nutricenter-container
            docker rm nutricenter-container
        fi
        
        # Eliminar la imagen si existe
        if [ "$(docker images -q nutricenter-api)" ]; then
            docker rmi nutricenter-api
        fi
        
        # Pull de los últimos cambios
        git pull origin main
        
        # Reconstruir y ejecutar el contenedor
        docker build -t nutricenter-api .
        docker run -d --name nutricenter-container -p 8080:8080 -p 8081:8081 nutricenter-api
        
        echo "Despliegue completado con éxito"
        EOF
